### ISSUE TITLE
cargo install chimper fails on glium 0.16

### ISSUE THREAD

**Issue by eddy-geek** [pedrocr/chimper#5]
cargo install fails, I guess glium version is outdated or removed from registry?

```
cargo install chimper
 Downloading chimper v0.1.0
  Installing chimper v0.1.0
    Updating git repository `https://github.com/tomaka/glium.git`
error: failed to compile `chimper v0.1.0`, intermediate artifacts can be found at `/tmp/cargo-install.0blz3OGJdOfu`

Caused by:
  no matching package for override `https://github.com/rust-lang/crates.io-index#glium:0.16.0` found
location searched: https://github.com/tomaka/glium.git
version required: = 0.16.0
```

**Comment by pedrocr** [comment]
Thanks for reporting it, should be fixed now. Did a whole bunch of dependency updates to use only registry versions now that my patches are all upstream in released versions.

If you want to discuss chimper or image/raw processing in rust feel free to stop by #chimper on irc.mozilla.org
